apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: event-backbone
  namespace: eventstreams
spec:
  adminApi: {}
  adminUI: {}
  apicurioRegistry: {}
  license:
    accept: true
    use: CloudPakForIntegrationNonProduction
  requestIbmServices:
    iam: true
    monitoring: true
  restProducer: {}
  strimziOverrides:
    entityOperator:
      topicOperator: {}
    kafka:
      authorization:
        authorizerClass: com.ibm.eventstreams.runas.authorizer.RunAsAuthorizer
        supportsAdminApi: true
        type: custom
      config:
        num.network.threads: 3
        inter.broker.protocol.version: '3.2'
        log.cleaner.threads: 6
        num.io.threads: 24
        num.replica.fetchers: 1
        min.insync.replicas: 1
        log.message.format.version: '3.2'
        offsets.topic.replication.factor: 1
        default.replication.factor: 1
      listeners:
        - authentication:
            type: scram-sha-512
          name: external
          port: 9094
          tls: true
          type: route
        - authentication:
            type: scram-sha-512
          name: tls
          port: 9093
          tls: true
          type: internal
      replicas: 1
      storage:
        type: ephemeral
    zookeeper:
      replicas: 1
      storage:
        type: ephemeral
  version: 11.0.4
